# Generated by Django 4.2.20 on 2025-05-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='partner',
        ),
        migrations.AddField(
            model_name='person',
            name='partners',
            field=models.ManyToManyField(blank=True, to='familytree.person'),
        ),
    ]
