# Generated by Django 4.2.20 on 2025-04-07 13:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_person_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
