# Generated by Django 4.2.20 on 2025-06-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_remove_person_partner_person_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyrelation',
            name='relation_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('step-parent', 'Step Parent'), ('foster-parent', 'Foster Parent'), ('child', 'Child'), ('step-child', 'Step Child'), ('foster-child', 'Foster Child'), ('sibling', 'Sibling'), ('half-sibling', 'Half Sibling'), ('step-sibling', 'Step Sibling'), ('partner', 'Romantic Partner'), ('ex-partner', 'Ex Romantic Partner'), ('deceased', 'Deceased Partner')], max_length=50),
        ),
    ]
